### PR TITLE
Care-O-Bot4 (Cob4) resources for robowflex

### PR DESCRIPTION
**Pull request by juandhv**
Care-O-Bot4 (Cob4) is a dual-arm service robot. This PR includes the Cob4 resources (URDF, meshes, etc.) and the MoveIt! configurations for two planning groups (arm_left and arm_right).

### CODE REVIEW

**Comment by zkingston** [comment]
Can you add a cob4.yml at the top-level? Take a look at the other robot implementations there.

**Comment by juandhv** [comment]
Thanks for reviewing this change @zkingston. I've added a cob4.yml

**Review by zkingston — APPROVED** [review]

**Comment by zkingston** [comment]
@juandhv sorry, can you also add a link in the README to the source repository for this robot?

**Comment by juandhv** [comment]
Done, @zkingston !

**Pull request merged**
